### ISSUE TITLE
strings_en.h: No such file or directory

### ISSUE THREAD

**Issue by ochm** [sergejbubko/HODLcube#1]
Hi all,

sorry for maybe stupid question, but i have probably all libraries installed,
but at begin of compilation i see error 
HODLcube:47:10: error: strings_en.h: No such file or directory
   47 | #include <strings_en.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
I found the file in https://github.com/tzapu/WiFiManager/tree/feature_asyncwebserver
so i copied the file to library directory of WiFiManager which was installed from the same github source.
Now the file is not missing, but I'm receiving lot of errors in compilation.

Tested on Arduino IDE 1.8.8 an 1.8.16

Thank you.

In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:19: error: 'HTTP_ANY' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                   ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:69:3: note: previous declaration 'WebRequestMethod HTTP_ANY'
   69 |   HTTP_ANY     = 0b01111111,
      |   ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:29: error: 'HTTP_GET' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                             ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:62:3: note: previous declaration 'WebRequestMethod HTTP_GET'
   62 |   HTTP_GET     = 0b00000001,
      |   ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:39: error: 'HTTP_HEAD' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                       ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:67:3: note: previous declaration 'WebRequestMethod HTTP_HEAD'
   67 |   HTTP_HEAD    = 0b00100000,
      |   ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:50: error: 'HTTP_POST' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                                  ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:63:3: note: previous declaration 'WebRequestMethod HTTP_POST'
   63 |   HTTP_POST    = 0b00000010,
      |   ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:61: error: 'HTTP_PUT' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                                             ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:65:3: note: previous declaration 'WebRequestMethod HTTP_PUT'
   65 |   HTTP_PUT     = 0b00001000,
      |   ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:71: error: 'HTTP_PATCH' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                                                       ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:66:3: note: previous declaration 'WebRequestMethod HTTP_PATCH'
   66 |   HTTP_PATCH   = 0b00010000,
      |   ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:83: error: 'HTTP_DELETE' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                                                                   ^~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:64:3: note: previous declaration 'WebRequestMethod HTTP_DELETE'
   64 |   HTTP_DELETE  = 0b00000100,
      |   ^~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:47:96: error: 'HTTP_OPTIONS' conflicts with a previous declaration
   47 | enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_HEAD, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };
      |                                                                                                ^~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:45:
C:\Users\doma\Documents\Arduino\libraries\ESPAsyncWebServer/ESPAsyncWebServer.h:68:3: note: previous declaration 'WebRequestMethod HTTP_OPTIONS'
   68 |   HTTP_OPTIONS = 0b01000000,
      |   ^~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:26:12: error: redefinition of 'const char HTTP_STYLE []'
   26 | const char HTTP_STYLE[] PROGMEM           = "<style>.c{text-align: center;} div,input{padding:5px;font-size:1em;} input{width:95%;} body{text-align: center;font-family:verdana;} button{border:0;border-radius:0.3rem;background-color:#1fa3ec;color:#fff;line-height:2.4rem;font-size:1.2rem;width:100%;} .q{float: right;width: 64px;text-align: right;} .l{background: url(\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAALVBMVEX///8EBwfBwsLw8PAzNjaCg4NTVVUjJiZDRUUUFxdiZGSho6OSk5Pg4eFydHTCjaf3AAAAZElEQVQ4je2NSw7AIAhEBamKn97/uMXEGBvozkWb9C2Zx4xzWykBhFAeYp9gkLyZE0zIMno9n4g19hmdY39scwqVkOXaxph0ZCXQcqxSpgQpONa59wkRDOL93eAXvimwlbPbwwVAegLS1HGfZAAAAABJRU5ErkJggg==\") no-repeat left center;background-size: 1em;}</style>";
      |            ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:81:12: note: 'const char HTTP_STYLE [2781]' previously defined here
   81 | const char HTTP_STYLE[]            PROGMEM = "<style>"
      |            ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:27:12: error: redefinition of 'const char HTTP_SCRIPT []'
   27 | const char HTTP_SCRIPT[] PROGMEM          = "<script>function c(l){document.getElementById('s').value=l.innerText||l.textContent;document.getElementById('p').focus();}</script>";
      |            ^~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:26:12: note: 'const char HTTP_SCRIPT [229]' previously defined here
   26 | const char HTTP_SCRIPT[]           PROGMEM = "<script>function c(l){"
      |            ^~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:29:12: error: redefinition of 'const char HTTP_PORTAL_OPTIONS []'
   29 | const char HTTP_PORTAL_OPTIONS[] PROGMEM  = "<form action=\"/wifi\" method=\"get\"><button>Configure WiFi</button></form><br/><form action=\"/0wifi\" method=\"get\"><button>Configure WiFi (No Scan)</button></form><br/><form action=\"/i\" method=\"get\"><button>Info</button></form><br/><form action=\"/r\" method=\"post\"><button>Reset</button></form>";
      |            ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:50:12: note: 'const char HTTP_PORTAL_OPTIONS [1]' previously defined here
   50 | const char HTTP_PORTAL_OPTIONS[]   PROGMEM = "";
      |            ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:30:12: error: redefinition of 'const char HTTP_ITEM []'
   30 | const char HTTP_ITEM[] PROGMEM            = "<div><a href='#p' onclick='c(this)'>{v}</a>&nbsp;<span class='q {i}'>{r}%</span></div>";
      |            ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:53:12: note: 'const char HTTP_ITEM [58]' previously defined here
   53 | const char HTTP_ITEM[]             PROGMEM = "<div><a href='#p' onclick='c(this)'>{v}</a>{qi}{qp}</div>"; // {q} = HTTP_ITEM_QI, {r} = HTTP_ITEM_QP
      |            ^~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:31:12: error: redefinition of 'const char HTTP_FORM_START []'
   31 | const char HTTP_FORM_START[] PROGMEM      = "<form method='get' action='wifisave'><input id='s' name='s' length=32 placeholder='SSID'><br/><input id='p' name='p' length=64 type='password' placeholder='password'><br/>";
      |            ^~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:56:12: note: 'const char HTTP_FORM_START [34]' previously defined here
   56 | const char HTTP_FORM_START[]       PROGMEM = "<form method='POST' action='{v}'>";
      |            ^~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:32:12: error: redefinition of 'const char HTTP_FORM_PARAM []'
   32 | const char HTTP_FORM_PARAM[] PROGMEM      = "<br/><input id='{i}' name='{n}' maxlength={l} placeholder='{p}' value='{v}' {c}>";
      |            ^~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:63:12: note: 'const char HTTP_FORM_PARAM [65]' previously defined here
   63 | const char HTTP_FORM_PARAM[]       PROGMEM = "<br/><input id='{i}' name='{n}' maxlength='{l}' value='{v}' {c}>";
      |            ^~~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:33:12: error: redefinition of 'const char HTTP_FORM_END []'
   33 | const char HTTP_FORM_END[] PROGMEM        = "<br/><button type='submit'>save</button></form>";
      |            ^~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:60:12: note: 'const char HTTP_FORM_END [53]' previously defined here
   60 | const char HTTP_FORM_END[]         PROGMEM = "<br/><br/><button type='submit'>Save</button></form>";
      |            ^~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:34:12: error: redefinition of 'const char HTTP_SCAN_LINK []'
   34 | const char HTTP_SCAN_LINK[] PROGMEM       = "<br/><div class=\"c\"><a href=\"/wifi\">Scan</a></div>";
      |            ^~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:65:12: note: 'const char HTTP_SCAN_LINK [107]' previously defined here
   65 | const char HTTP_SCAN_LINK[]        PROGMEM = "<br/><form action='/wifi?refresh=1' method='POST'><button name='refresh' value='1'>Refresh</button></form>";
      |            ^~~~~~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:35:12: error: redefinition of 'const char HTTP_SAVED []'
   35 | const char HTTP_SAVED[] PROGMEM           = "<div>Credentials Saved<br />Trying to connect ESP to network.<br />If it fails reconnect to AP to try again</div>";
      |            ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:66:12: note: 'const char HTTP_SAVED [126]' previously defined here
   66 | const char HTTP_SAVED[]            PROGMEM = "<div class='msg'>Saving Credentials<br/>Trying to connect ESP to network.<br />If it fails reconnect to AP to try again</div>";
      |            ^~~~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:36:12: error: redefinition of 'const char HTTP_END []'
   36 | const char HTTP_END[] PROGMEM             = "</div></body></html>";
      |            ^~~~~~~~
In file included from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:47:
C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/strings_en.h:68:12: note: 'const char HTTP_END [21]' previously defined here
   68 | const char HTTP_END[]              PROGMEM = "</div></body></html>";
      |            ^~~~~~~~
HODLcube:125:13: error: conflicting declaration 'const char* filename'
  125 | const char *filename = "/settings.txt";
      |             ^~~~~~~~
In file included from C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/ESP8266WebServer.h:341,
                 from C:\Users\doma\Documents\Arduino\libraries\WiFiManager-0.16.0/WiFiManager.h:17,
                 from C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino:49:
C:\Users\doma\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WebServer\src/Parsing-impl.h:33:19: note: previous declaration as 'const char filename [9]'
   33 | static const char filename[] PROGMEM = "filename";
      |                   ^~~~~~~~
C:\Users\doma\Documents\Arduino\HODLcube-0.4.0\HODLcube\HODLcube.ino: In function 'void setup()':
HODLcube:391:6: error: 'class WiFiManager' has no member named 'setMenu'
  391 |   wm.setMenu(menu);
      |      ^~~~~~~
exit status 1
conflicting declaration 'const char* filename'

**Comment by sergejbubko** [comment]
Hi, please be sure to download correct version of WifiManager using [link](https://github.com/tzapu/WiFiManager/tree/feature_asyncwebserver) mentioned in source code: 

```
#include <strings_en.h>
// https://github.com/tzapu/WiFiManager/tree/feature_asyncwebserver
#include <WiFiManager.h>  
```

You are using WifiManager v0.16.0, that won't work for sure.

Have a nice day.

V.

**Comment by ochm** [comment]
I used the link, and there is on right side Latest release and link to 0.16. 
If it is not correct version, which release i need to download from release page 
https://github.com/tzapu/WiFiManager/releases
Or the right file is https://github.com/tzapu/WiFiManager/archive/refs/heads/feature_asyncwebserver.zip?
Thank you.

**Comment by sergejbubko** [comment]
feature_asyncwebserver is correct branch to download, so yes this link https://github.com/tzapu/WiFiManager/archive/refs/heads/feature_asyncwebserver.zip is fine

**Comment by ochm** [comment]
OK, thank you very much, everything goes well during compilation, the result is:
Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 519220          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 29153   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1540  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 5340  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 27432 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 555253 bytes (53%) of program storage space. Maximum is 1044464 bytes.
Global variables use 34312 bytes (41%) of dynamic memory, leaving 47608 bytes for local variables. Maximum is 81920 bytes.

Arduino IDE shows me now that some libraries are available for update:
NTPClient 3.1.0 to 3.2.0
Adafruit Circuit Playground 1.1.13 to 1.1.14
WiFiManager 2.0.4-beta to 2.0.5-beta
Is it safe to do updates or not? 
My apologise for maybe stupid quiestions, but i'm using Arduino IDE maybe once per year.
